### ISSUE TITLE
Export IPD

### ISSUE THREAD

**Issue by wildermuthn** [wwwtyro/node-ovrsdk#2]
Is it possible to grab the IPD value from the Oculus Configuration settings?

**Comment by wwwtyro** [comment]
Thanks for the request. I'll see if I can get it working tonight. :)

**Comment by wwwtyro** [comment]
Okay, it's possible to get it through the C API, but not quite as easily as something like `userProfile.getIPD()`, unfortunately.

Here's how I acquired it in the test (test.js):

``` javascript
console.log("Getting ovrEyeRenderDesc for left eye...".cyan.bold);
var lerd = libovr.ovrHmd_GetRenderDesc(hmd, libovr.ovrEye_Left, desc.DefaultEyeFov[0]);
console.log("View Adjust, left eye x-component".blue.bold, lerd.ViewAdjust.x);

console.log("Getting ovrEyeRenderDesc for right eye...".cyan.bold);
var rerd = libovr.ovrHmd_GetRenderDesc(hmd, libovr.ovrEye_Right, desc.DefaultEyeFov[0]);
console.log("View Adjust, right eye x-component".blue.bold, rerd.ViewAdjust.x);
```

To get the full IPD, I think the proper approach would be to sum the two x-components. Hopefully I can get an example of rendering with their SDK rendering infrastructure working soon so that we won't have to fudge this, but this will have to do for now.

Thanks again for the request - I'm using these to drive the development, so it really is a big help to know what people need.

**Comment by wildermuthn** [comment]
This is great, thanks! I'll try it out. I worked on this all last night, and will be more active here with issues as I stumble upon things. 

It would be great to get the new SDK implemented.
